import {
  AREA_MEASUREMENT,
  CURRENCY_TYPE,
  LISTING_PURPOSE,
  PRICE_FREQUENCY,
  PROPERTY_STATUS,
  PROPERTY_SUB_TYPE,
  PROPERTY_TYPE,
} from '@modules/property/schemas/property.schema';

export const PROPERTY_ENUMS = {
  PROPERTY_STATUS,
  PROPERTY_SUB_TYPE,
  PROPERTY_TYPE,
  LISTING_PURPOSE,
  CURRENCY_TYPE,
  AREA_MEASUREMENT,
  PRICE_FREQUENCY,
};
