const users = [{"name":"Sibley","email":"scullip0@mysql.com","password":"Tester@01"},
    {"name":"Federica","email":"fblagbrough1@amazon.co.uk","password":"Tester@01"},
    {"name":"Hayyim","email":"hilyin2@360.cn","password":"Tester@01"},
    {"name":"Andee","email":"aetoile3@zdnet.com","password":"Tester@01"},
    {"name":"Allianora","email":"abuddock4@hp.com","password":"Tester@01"},
    {"name":"Aguie","email":"adomengue5@cbc.ca","password":"Tester@01"},
    {"name":"Bo","email":"bkock6@freewebs.com","password":"Tester@01"},
    {"name":"Chevy","email":"cchevis7@omniture.com","password":"Tester@01"},
    {"name":"Gertrudis","email":"gblesdill8@hp.com","password":"Tester@01"},
    {"name":"Nertie","email":"ngarms9@blinklist.com","password":"Tester@01"},
    {"name":"Lamar","email":"ltorresea@va.gov","password":"Tester@01"},
    {"name":"Brunhilda","email":"bsetterthwaitb@businessweek.com","password":"Tester@01"},
    {"name":"Nestor","email":"ncowwellc@blinklist.com","password":"Tester@01"},
    {"name":"Lorry","email":"ldammarelld@nymag.com","password":"Tester@01"},
    {"name":"Joe","email":"jporkisse@adobe.com","password":"Tester@01"},
    {"name":"Harmonie","email":"hbolerf@marketwatch.com","password":"Tester@01"},
    {"name":"Andrea","email":"amcettrickg@hatena.ne.jp","password":"Tester@01"},
    {"name":"Nat","email":"nbrosiush@dmoz.org","password":"Tester@01"},
    {"name":"Lotte","email":"ljacmardi@cafepress.com","password":"Tester@01"},
    {"name":"Leon","email":"lbeilbyj@smugmug.com","password":"Tester@01"},
    {"name":"Beilul","email":"bcaenk@toplist.cz","password":"Tester@01"},
    {"name":"Zachary","email":"zmcphilipl@usnews.com","password":"Tester@01"},
    {"name":"Meggy","email":"mroubaym@bigcartel.com","password":"Tester@01"},
    {"name":"Jakie","email":"jbrimilcomben@etsy.com","password":"Tester@01"},
    {"name":"Keriann","email":"kollivero@ed.gov","password":"Tester@01"},
    {"name":"Min","email":"mdunbobinp@wufoo.com","password":"Tester@01"},
    {"name":"Donni","email":"dferroneq@myspace.com","password":"Tester@01"},
    {"name":"Aloin","email":"ahoovartr@tinyurl.com","password":"Tester@01"},
    {"name":"Carole","email":"ccosanss@exblog.jp","password":"Tester@01"},
    {"name":"Rowena","email":"rkoenent@cisco.com","password":"Tester@01"},
    {"name":"Nero","email":"npancostu@usa.gov","password":"Tester@01"},
    {"name":"Jedidiah","email":"jschultheissv@netvibes.com","password":"Tester@01"},
    {"name":"Ingunna","email":"iwithringtonw@ning.com","password":"Tester@01"},
    {"name":"Agnella","email":"asawdyx@theguardian.com","password":"Tester@01"},
    {"name":"Lona","email":"lfosbraeyy@prnewswire.com","password":"Tester@01"},
    {"name":"Matty","email":"mkleinez@cbslocal.com","password":"Tester@01"},
    {"name":"Cordelia","email":"cbaynton10@ehow.com","password":"Tester@01"},
    {"name":"Rab","email":"rgraser11@studiopress.com","password":"Tester@01"},
    {"name":"Kelley","email":"ksheppey12@creativecommons.org","password":"Tester@01"},
    {"name":"Thorsten","email":"tbusch13@unesco.org","password":"Tester@01"},
    {"name":"Boony","email":"bgabb14@state.tx.us","password":"Tester@01"},
    {"name":"Weider","email":"wfagg15@amazon.de","password":"Tester@01"},
    {"name":"Viviyan","email":"vantonioni16@mozilla.org","password":"Tester@01"},
    {"name":"Candy","email":"cguilfoyle17@vistaprint.com","password":"Tester@01"},
    {"name":"Persis","email":"pwillatts18@apache.org","password":"Tester@01"},
    {"name":"Dory","email":"dtitterington19@aboutads.info","password":"Tester@01"},
    {"name":"Justina","email":"jhassewell1a@geocities.jp","password":"Tester@01"},
    {"name":"Chuck","email":"cosment1b@fotki.com","password":"Tester@01"},
    {"name":"Raphael","email":"rreilly1c@google.it","password":"Tester@01"},
    {"name":"Hersh","email":"hkhalid1d@1und1.de","password":"Tester@01"},
    {"name":"Luise","email":"lserver1e@google.com.au","password":"Tester@01"},
    {"name":"Kin","email":"ktolley1f@angelfire.com","password":"Tester@01"},
    {"name":"Sharline","email":"sjoutapaitis1g@yahoo.co.jp","password":"Tester@01"},
    {"name":"Ashby","email":"acassam1h@jimdo.com","password":"Tester@01"},
    {"name":"Lenette","email":"lhillan1i@vimeo.com","password":"Tester@01"},
    {"name":"Ewen","email":"etribbeck1j@cafepress.com","password":"Tester@01"},
    {"name":"Clarette","email":"cvine1k@dmoz.org","password":"Tester@01"},
    {"name":"Wendy","email":"wprahl1l@over-blog.com","password":"Tester@01"},
    {"name":"Alexis","email":"alaise1m@chicagotribune.com","password":"Tester@01"},
    {"name":"Cacilia","email":"cteek1n@google.es","password":"Tester@01"},
    {"name":"Lay","email":"lmatteau1o@odnoklassniki.ru","password":"Tester@01"},
    {"name":"Wain","email":"wfernant1p@ibm.com","password":"Tester@01"},
    {"name":"Berty","email":"beffnert1q@ocn.ne.jp","password":"Tester@01"},
    {"name":"Broderic","email":"bramm1r@spiegel.de","password":"Tester@01"},
    {"name":"Keary","email":"kzanettini1s@europa.eu","password":"Tester@01"},
    {"name":"Beatrix","email":"bedie1t@ft.com","password":"Tester@01"},
    {"name":"Boniface","email":"btottle1u@vinaora.com","password":"Tester@01"},
    {"name":"Minor","email":"mclynter1v@typepad.com","password":"Tester@01"},
    {"name":"Delaney","email":"dkeyes1w@squidoo.com","password":"Tester@01"},
    {"name":"Inglebert","email":"iokynsillaghe1x@livejournal.com","password":"Tester@01"},
    {"name":"Clim","email":"cjerman1y@ca.gov","password":"Tester@01"},
    {"name":"Adina","email":"apeatman1z@tripadvisor.com","password":"Tester@01"},
    {"name":"Sheba","email":"slawson20@nydailynews.com","password":"Tester@01"},
    {"name":"Madeline","email":"mpeschet21@bbb.org","password":"Tester@01"},
    {"name":"Maryanne","email":"mtallowin22@cnbc.com","password":"Tester@01"},
    {"name":"Petronilla","email":"plongega23@patch.com","password":"Tester@01"},
    {"name":"Tyrone","email":"tmcilwrick24@arizona.edu","password":"Tester@01"},
    {"name":"Olvan","email":"onealy25@dell.com","password":"Tester@01"},
    {"name":"Merline","email":"msanpher26@cbsnews.com","password":"Tester@01"},
    {"name":"Estrella","email":"ecarlin27@vkontakte.ru","password":"Tester@01"},
    {"name":"Portie","email":"psommerton28@github.io","password":"Tester@01"},
    {"name":"Inger","email":"isylvester29@economist.com","password":"Tester@01"},
    {"name":"Hyman","email":"hhurdman2a@ning.com","password":"Tester@01"},
    {"name":"Dixie","email":"dkelk2b@pen.io","password":"Tester@01"},
    {"name":"Devondra","email":"dbickell2c@europa.eu","password":"Tester@01"},
    {"name":"Cari","email":"cantunes2d@newsvine.com","password":"Tester@01"},
    {"name":"Jacinta","email":"jheffer2e@amazon.co.jp","password":"Tester@01"},
    {"name":"Georas","email":"gaskaw2f@ibm.com","password":"Tester@01"},
    {"name":"Martainn","email":"mtitchen2g@ftc.gov","password":"Tester@01"},
    {"name":"Rodi","email":"rkristiansen2h@shareasale.com","password":"Tester@01"},
    {"name":"Orren","email":"oubsdall2i@independent.co.uk","password":"Tester@01"},
    {"name":"Venita","email":"vwinsley2j@constantcontact.com","password":"Tester@01"},
    {"name":"Steffane","email":"sgulston2k@so-net.ne.jp","password":"Tester@01"},
    {"name":"Zacharia","email":"zrenwick2l@cdc.gov","password":"Tester@01"},
    {"name":"Tomlin","email":"tcobbing2m@de.vu","password":"Tester@01"},
    {"name":"Daveta","email":"dtysack2n@exblog.jp","password":"Tester@01"},
    {"name":"Jules","email":"jilden2o@theglobeandmail.com","password":"Tester@01"},
    {"name":"Carol","email":"cmacgrath2p@sourceforge.net","password":"Tester@01"},
    {"name":"Hashim","email":"hmcmurthy2q@va.gov","password":"Tester@01"},
    {"name":"Belia","email":"bhulett2r@miibeian.gov.cn","password":"Tester@01"}
]

async function register(user) {
    const response = await fetch('http://localhost:4003/api/v1/auth/register',{
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(user)
    })
    const data = await response.json()
    console.log(data)
}

async function seed() {
    for (let user of users) {
        await register(user)
    }
}

seed()